"""Spawn `prime rl` / `prime gepa` subprocesses; parse metrics.

`prime rl` is local-only (it's the deprecated alias for `prime train`; takes a
TOML config positional). `prime gepa` is also local-only. Both stream stdout
that we tail for scalar metrics.

Public API (per `tools/launchpad/CONTRACTS.md` section 5):
    materialize_rl_toml(spec, dest) -> Path
    launch_rl(spec, repo_root) -> str
    launch_gepa(spec, repo_root) -> str
    stream_metrics(task_id) -> AsyncIterator[TrainMetric]
    stream_events(task_id) -> AsyncIterator[TaskEvent]
    stop_task(task_id) -> bool
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import shutil
import signal
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, AsyncIterator

from tools.launchpad.types import TaskEvent, TrainMetric, TrainSpec

logger = logging.getLogger(__name__)

# Grace period before escalating SIGTERM -> SIGKILL.
_KILL_GRACE_S: float = 5.0

# Regexes for parsing scalar metrics from stdout.
# Matches `name=value`, `name: value`, or `name value` segments with floats.
_METRIC_KV_RE = re.compile(
    r"(?P<name>[A-Za-z_][A-Za-z0-9_/\.]*)\s*[:=]\s*(?P<value>-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)"
)
_STEP_RE = re.compile(
    r"\b(?:step|global[_-]?step|iter(?:ation)?)\s*[:=]\s*(?P<step>\d+)", re.IGNORECASE
)
# Known scalar metric names we forward; anything matching `eval/...` also passes.
_KNOWN_METRIC_NAMES: frozenset[str] = frozenset(
    {
        "loss",
        "kl",
        "reward",
        "grad_norm",
        "lr",
        "entropy",
        "pg_loss",
        "value_loss",
        "policy_loss",
        "advantage",
    }
)


def _is_metric_name(name: str) -> bool:
    if name in _KNOWN_METRIC_NAMES:
        return True
    if name.startswith("eval/") or name.startswith("eval_"):
        return True
    # GEPA population stats, e.g. `pop/best`, `pop/mean`, `gepa/reward`.
    if name.startswith("pop/") or name.startswith("gepa/"):
        return True
    return False


@dataclass
class _Task:
    """Tracking record for one launched subprocess.

    Subscribers (stream_metrics / stream_events) get a replay of everything
    seen so far plus all future items; this avoids subscribe-race losses if
    the pumps drain stdout before the consumer subscribes.
    """

    task_id: str
    process: asyncio.subprocess.Process
    started_at: float
    current_step: int = 0
    metric_log: list[TrainMetric] = field(default_factory=list)
    event_log: list[TaskEvent] = field(default_factory=list)
    finished: bool = False
    metric_cond: asyncio.Condition | None = None
    event_cond: asyncio.Condition | None = None
    reader_tasks: list[asyncio.Task[None]] = field(default_factory=list)


# Registry. Module-global per CONTRACTS section 8 (registries are the allowed
# exception to the "no global state" rule).
_TASKS: dict[str, _Task] = {}


# ---------------------------------------------------------------------------
# TOML materialization
# ---------------------------------------------------------------------------


def _toml_escape(s: str) -> str:
    """Escape a string for a TOML basic-string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _atomic_write_text(dest: Path, text: str) -> None:
    """Write `text` to `dest` atomically (tempfile in same dir + rename)."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path_str = tempfile.mkstemp(
        prefix=f".{dest.name}.", suffix=".tmp", dir=str(dest.parent)
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, dest)
    except BaseException:
        try:
            tmp_path.unlink()
        except FileNotFoundError:
            pass
        raise


def materialize_rl_toml(spec: TrainSpec, dest: Path) -> Path:
    """Write a `prime rl`-compatible TOML config from `spec` to `dest`.

    Raises:
        ValueError: if `spec.mode != 'rl'` or required fields are missing.
    """
    if spec.mode != "rl":
        raise ValueError(f"materialize_rl_toml: expected mode='rl', got {spec.mode!r}")
    if not spec.base_model:
        raise ValueError("materialize_rl_toml: spec.base_model is required for mode='rl'")
    if spec.hparams is None:
        raise ValueError("materialize_rl_toml: spec.hparams is required for mode='rl'")

    hp = spec.hparams
    lines: list[str] = []
    lines.append(f'# Auto-generated by tools.launchpad.core.trainer for label={spec.label!r}')
    lines.append("")
    lines.append("[run]")
    lines.append(f'label = "{_toml_escape(spec.label)}"')
    lines.append(f'harness = "{_toml_escape(spec.harness)}"')
    lines.append("")
    lines.append("[model]")
    lines.append(f'base = "{_toml_escape(spec.base_model)}"')
    lines.append("")
    lines.append("[hparams]")
    lines.append(f"lr = {hp.lr!r}")
    lines.append(f"kl_coef = {hp.kl_coef!r}")
    lines.append(f"group_size = {hp.group_size}")
    lines.append(f"rollouts_per_example = {hp.rollouts_per_example}")
    lines.append(f"max_turns = {hp.max_turns}")
    lines.append(f"batch_size = {hp.batch_size}")
    lines.append("")
    lines.append("[env]")
    lines.append("name = \"nethack\"")
    if spec.tiers:
        tiers_arr = ", ".join(f'"{_toml_escape(t)}"' for t in spec.tiers)
        lines.append(f"tiers = [{tiers_arr}]")
    if spec.filtering is not None:
        lines.append("")
        lines.append("[filtering]")
        lines.append(f"min_difficulty = {spec.filtering.min_difficulty!r}")
        lines.append(f"max_difficulty = {spec.filtering.max_difficulty!r}")
        lines.append(f"oversample_hard = {str(spec.filtering.oversample_hard).lower()}")
    if spec.eval is not None:
        lines.append("")
        lines.append("[eval]")
        lines.append(f"every_steps = {spec.eval.every_steps}")
        lines.append(f"n_examples = {spec.eval.n_examples}")
        if spec.eval.tiers:
            tiers_arr = ", ".join(f'"{_toml_escape(t)}"' for t in spec.eval.tiers)
            lines.append(f"tiers = [{tiers_arr}]")

    text = "\n".join(lines) + "\n"
    _atomic_write_text(dest, text)
    logger.info("materialize_rl_toml: wrote %s (%d bytes)", dest, len(text))
    return dest


# ---------------------------------------------------------------------------
# Subprocess launch
# ---------------------------------------------------------------------------


def _ensure_prime_on_path() -> str:
    """Return the absolute path to `prime`, or raise FileNotFoundError."""
    prime = shutil.which("prime")
    if prime is None:
        raise FileNotFoundError("`prime` CLI not found on PATH")
    return prime


def _make_task_id(label: str) -> str:
    return f"{label}_{int(time.time())}"


def _register_task(
    task_id: str, process: asyncio.subprocess.Process, started_at: float
) -> _Task:
    task = _Task(
        task_id=task_id,
        process=process,
        started_at=started_at,
        metric_cond=asyncio.Condition(),
        event_cond=asyncio.Condition(),
    )
    _TASKS[task_id] = task
    # Spawn the reader pumps now (so output flows even with no consumers).
    task.reader_tasks.append(
        asyncio.create_task(_pump_stream(task, process.stdout, "stdout"))
    )
    task.reader_tasks.append(
        asyncio.create_task(_pump_stream(task, process.stderr, "stderr"))
    )
    task.reader_tasks.append(asyncio.create_task(_pump_finished(task)))
    return task


async def _publish_event(task: _Task, event: TaskEvent) -> None:
    assert task.event_cond is not None
    async with task.event_cond:
        task.event_log.append(event)
        task.event_cond.notify_all()


async def _publish_metric(task: _Task, metric: TrainMetric) -> None:
    assert task.metric_cond is not None
    async with task.metric_cond:
        task.metric_log.append(metric)
        task.metric_cond.notify_all()


async def _mark_finished(task: _Task) -> None:
    assert task.event_cond is not None and task.metric_cond is not None
    task.finished = True
    async with task.event_cond:
        task.event_cond.notify_all()
    async with task.metric_cond:
        task.metric_cond.notify_all()


async def launch_rl(spec: TrainSpec, repo_root: Path) -> str:
    """Launch `prime rl <toml>`. Returns task_id."""
    if spec.mode != "rl":
        raise ValueError(f"launch_rl: expected mode='rl', got {spec.mode!r}")
    prime = _ensure_prime_on_path()

    toml_dir = repo_root / "runs" / "rl" / spec.label
    toml_path = toml_dir / "config.toml"
    materialize_rl_toml(spec, toml_path)

    argv = [prime, "rl", str(toml_path)]
    env = os.environ.copy()
    env["NETHACK_HARNESS"] = spec.harness

    logger.info("launch_rl: argv=%s", argv)
    process = await asyncio.create_subprocess_exec(
        *argv,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=str(repo_root),
        env=env,
    )
    task_id = _make_task_id(spec.label)
    _register_task(task_id, process, time.time())
    return task_id


async def launch_gepa(spec: TrainSpec, repo_root: Path) -> str:
    """Launch `prime gepa run nethack ...`. Returns task_id."""
    if spec.mode != "gepa":
        raise ValueError(f"launch_gepa: expected mode='gepa', got {spec.mode!r}")
    if not spec.proposer_model:
        raise ValueError("launch_gepa: spec.proposer_model is required for mode='gepa'")
    prime = _ensure_prime_on_path()

    population = spec.population or 4
    generations = spec.generations or 4
    max_calls = population * generations
    # `n_examples` source: prefer eval.n_examples; fall back to 8.
    n_examples = spec.eval.n_examples if spec.eval is not None else 8

    env_args_json = json.dumps({}, separators=(",", ":"))

    run_dir = repo_root / "runs" / "gepa" / spec.label

    argv = [
        prime,
        "gepa",
        "run",
        "nethack",
        "--env-args",
        env_args_json,
        "--model",
        spec.proposer_model,
        "--reflection-model",
        spec.proposer_model,
        "--max-calls",
        str(max_calls),
        "--num-train",
        str(n_examples),
        "--num-val",
        str(n_examples),
        "--run-dir",
        str(run_dir),
    ]
    env = os.environ.copy()
    env["NETHACK_HARNESS"] = spec.harness

    logger.info("launch_gepa: argv=%s", argv)
    process = await asyncio.create_subprocess_exec(
        *argv,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=str(repo_root),
        env=env,
    )
    task_id = _make_task_id(spec.label)
    _register_task(task_id, process, time.time())
    return task_id


# ---------------------------------------------------------------------------
# Stdout/stderr pumps + parsing
# ---------------------------------------------------------------------------


def _parse_metrics_from_line(line: str, task_id: str) -> tuple[int | None, list[TrainMetric]]:
    """Pull (step, [metrics]) from a single stdout line.

    Returns (step_if_present, list_of_metrics). The caller threads `step` across
    lines so metrics on a subsequent line are tagged with the last-seen step.
    """
    step: int | None = None
    step_match = _STEP_RE.search(line)
    if step_match is not None:
        try:
            step = int(step_match.group("step"))
        except ValueError:
            step = None

    metrics: list[TrainMetric] = []
    t_wall = time.time()
    for m in _METRIC_KV_RE.finditer(line):
        name = m.group("name")
        if name in {"step", "global_step", "global-step", "iter", "iteration"}:
            continue
        if not _is_metric_name(name):
            continue
        try:
            value = float(m.group("value"))
        except ValueError:
            continue
        metrics.append(
            TrainMetric(
                task_id=task_id, step=step if step is not None else 0,
                t_wall=t_wall, name=name, value=value,
            )
        )
    return step, metrics


async def _pump_stream(
    task: _Task, stream: asyncio.StreamReader | None, kind: str
) -> None:
    """Read one stdio stream, fan out to event queues + (stdout only) metric queues."""
    if stream is None:
        return
    try:
        while True:
            try:
                raw = await stream.readline()
            except asyncio.CancelledError:
                raise
            except (ValueError, OSError) as exc:
                # readline may raise on giant lines or closed transport.
                logger.warning("task %s: %s read error: %s", task.task_id, kind, exc)
                break
            if not raw:
                break
            try:
                line = raw.decode("utf-8", errors="replace").rstrip("\n")
            except UnicodeDecodeError:
                line = raw.decode("latin-1", errors="replace").rstrip("\n")

            event = TaskEvent(
                task_id=task.task_id,
                kind="stdout" if kind == "stdout" else "stderr",
                t_wall=time.time(),
                payload={"line": line},
            )
            await _publish_event(task, event)

            if kind == "stdout":
                step, metrics = _parse_metrics_from_line(line, task.task_id)
                if step is not None:
                    task.current_step = step
                # Tag any unstepped metrics with last-known step.
                for met in metrics:
                    if met.step == 0 and task.current_step:
                        met = met.model_copy(update={"step": task.current_step})
                    await _publish_metric(task, met)
    except asyncio.CancelledError:
        logger.debug("task %s: %s pump cancelled", task.task_id, kind)
        raise


async def _pump_finished(task: _Task) -> None:
    """Wait for process exit and broadcast a `finished` event."""
    exit_code: int = -1
    try:
        exit_code = await task.process.wait()
    except asyncio.CancelledError:
        raise
    finally:
        ec = task.process.returncode if task.process.returncode is not None else exit_code
        # Wait for stdout/stderr pumps to drain so consumers see all output
        # before the terminal `finished` event.
        for sub in task.reader_tasks:
            if sub is asyncio.current_task():
                continue
            try:
                await asyncio.wait_for(asyncio.shield(sub), timeout=1.0)
            except (asyncio.TimeoutError, asyncio.CancelledError):
                pass
            except Exception as exc:  # pump-internal failure is non-fatal here
                logger.warning("task %s: pump await error: %s", task.task_id, exc)
        final = TaskEvent(
            task_id=task.task_id,
            kind="finished",
            t_wall=time.time(),
            payload={"exit_code": ec},
        )
        await _publish_event(task, final)
        await _mark_finished(task)

    logger.info("task %s exited with code %d", task.task_id, exit_code)


# ---------------------------------------------------------------------------
# Streams
# ---------------------------------------------------------------------------


async def stream_metrics(task_id: str) -> AsyncIterator[TrainMetric]:
    """Yield TrainMetric objects parsed from the subprocess's stdout.

    Replays everything emitted so far, then follows new metrics until the
    process exits (and the log is fully drained).
    """
    if task_id not in _TASKS:
        raise KeyError(task_id)
    task = _TASKS[task_id]
    assert task.metric_cond is not None
    cursor = 0
    while True:
        async with task.metric_cond:
            while cursor >= len(task.metric_log) and not task.finished:
                await task.metric_cond.wait()
            batch = task.metric_log[cursor:]
            cursor = len(task.metric_log)
            done = task.finished
        for item in batch:
            yield item
        if done and cursor >= len(task.metric_log):
            return


async def stream_events(task_id: str) -> AsyncIterator[TaskEvent]:
    """Yield raw stdout/stderr/status/finished events."""
    if task_id not in _TASKS:
        raise KeyError(task_id)
    task = _TASKS[task_id]
    assert task.event_cond is not None
    cursor = 0
    while True:
        async with task.event_cond:
            while cursor >= len(task.event_log) and not task.finished:
                await task.event_cond.wait()
            batch = task.event_log[cursor:]
            cursor = len(task.event_log)
            done = task.finished
        for item in batch:
            yield item
        if done and cursor >= len(task.event_log):
            return


# ---------------------------------------------------------------------------
# Stop
# ---------------------------------------------------------------------------


def stop_task(task_id: str) -> bool:
    """SIGTERM, then SIGKILL after 5s grace. Returns True if killed.

    Schedules an async waiter; returns True iff a stop signal was delivered to
    a still-live process. (The async escalation continues in the background.)
    """
    task = _TASKS.get(task_id)
    if task is None:
        return False
    proc = task.process
    if proc.returncode is not None:
        return False
    try:
        proc.terminate()
    except ProcessLookupError:
        return False
    except OSError as exc:
        logger.warning("stop_task(%s): terminate failed: %s", task_id, exc)
        return False

    async def _escalate() -> None:
        try:
            await asyncio.wait_for(proc.wait(), timeout=_KILL_GRACE_S)
        except asyncio.TimeoutError:
            logger.warning(
                "stop_task(%s): SIGTERM grace expired, sending SIGKILL", task_id
            )
            try:
                proc.kill()
            except ProcessLookupError:
                pass
            except OSError as exc:
                logger.warning("stop_task(%s): kill failed: %s", task_id, exc)
        except asyncio.CancelledError:
            raise

    try:
        loop = asyncio.get_running_loop()
        loop.create_task(_escalate())
    except RuntimeError:
        # No running loop; cannot schedule escalation. SIGTERM was still sent.
        logger.debug("stop_task(%s): no running loop; skipping SIGKILL escalation", task_id)
    return True


# Re-export for tests / live module.
__all__ = [
    "materialize_rl_toml",
    "launch_rl",
    "launch_gepa",
    "stream_metrics",
    "stream_events",
    "stop_task",
]

# Silence "imported but unused" for `signal` — kept for documentation of the
# signals we send via proc.terminate()/kill() on POSIX.
_ = signal.SIGTERM
_ = (Any,)  # keep `Any` import alive even if unused above
